pipeline:
  identifier: Build_hashinyc_notes_app_cicd_1746725531180
  name: Build notes-app-cicd
  orgIdentifier: default
  projectIdentifier: CI_Pipeline
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1746652796717
        repoName: hashinyc/notes-app-cicd
  stages:
    - stage:
        name: docker build
        identifier: docker_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.DockerHub
                    repo: baiyun/notesappcicd
                    tags:
                      - latest
                    dockerfile: Dockerfile
